name: Code Quality

on:
  pull_request:
    branches: [ master ]
    types: [opened, edited, synchronize, reopened]

jobs:
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run Pylint
        run: |
          pylint -E ./honeybadger

      - name: Run Black
        run: |
          black --check --diff ./honeybadger
